spring:
  sql:
    init:
      mode: NEVER
  datasource:
    url: jdbc:mysql://localhost:3306/world
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true
    show-sql: true

